// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6sYKjqzlizIZ9QTlmujv4Zq0ZTJjabCQ',
    appId: '1:937491341183:web:83bcc22001bccccb76044a',
    messagingSenderId: '937491341183',
    projectId: 'rentbike-79e86',
    authDomain: 'rentbike-79e86.firebaseapp.com',
    storageBucket: 'rentbike-79e86.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtjfrwuu2P_tJ4sw8Mr23j0Br8jvnQhF0',
    appId: '1:937491341183:android:0a834bcdbd72f8b776044a',
    messagingSenderId: '937491341183',
    projectId: 'rentbike-79e86',
    storageBucket: 'rentbike-79e86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFCbrZP6W8YKCmzdahFMxL7uClIyGU_s0',
    appId: '1:937491341183:ios:aec730eed65c6b0d76044a',
    messagingSenderId: '937491341183',
    projectId: 'rentbike-79e86',
    storageBucket: 'rentbike-79e86.firebasestorage.app',
    iosBundleId: 'com.example.utsw51123150032',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFCbrZP6W8YKCmzdahFMxL7uClIyGU_s0',
    appId: '1:937491341183:ios:aec730eed65c6b0d76044a',
    messagingSenderId: '937491341183',
    projectId: 'rentbike-79e86',
    storageBucket: 'rentbike-79e86.firebasestorage.app',
    iosBundleId: 'com.example.utsw51123150032',
  );
}
