// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIDM2o8z119pS-HK_5Af1lWYPr75ZTUCY',
    appId: '1:871890581556:web:c02012f2c7e2bc69e7f261',
    messagingSenderId: '871890581556',
    projectId: 'uts-uas1125170150sitirosita',
    authDomain: 'uts-uas1125170150sitirosita.firebaseapp.com',
    storageBucket: 'uts-uas1125170150sitirosita.firebasestorage.app',
    measurementId: 'G-H0PD4TP3K4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0qK9NZS2so4eVBciYH6CpMcss22g5824',
    appId: '1:871890581556:android:3be606329bfdad71e7f261',
    messagingSenderId: '871890581556',
    projectId: 'uts-uas1125170150sitirosita',
    storageBucket: 'uts-uas1125170150sitirosita.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQKYoHlazBnoUSruI4iCgWOZxdoMmJhVk',
    appId: '1:871890581556:ios:38283ab6b81e0bd4e7f261',
    messagingSenderId: '871890581556',
    projectId: 'uts-uas1125170150sitirosita',
    storageBucket: 'uts-uas1125170150sitirosita.firebasestorage.app',
    iosBundleId: 'com.example.utsw51123150032',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQKYoHlazBnoUSruI4iCgWOZxdoMmJhVk',
    appId: '1:871890581556:ios:38283ab6b81e0bd4e7f261',
    messagingSenderId: '871890581556',
    projectId: 'uts-uas1125170150sitirosita',
    storageBucket: 'uts-uas1125170150sitirosita.firebasestorage.app',
    iosBundleId: 'com.example.utsw51123150032',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIDM2o8z119pS-HK_5Af1lWYPr75ZTUCY',
    appId: '1:871890581556:web:f26fc0210c86094ee7f261',
    messagingSenderId: '871890581556',
    projectId: 'uts-uas1125170150sitirosita',
    authDomain: 'uts-uas1125170150sitirosita.firebaseapp.com',
    storageBucket: 'uts-uas1125170150sitirosita.firebasestorage.app',
    measurementId: 'G-QQQMHNT3QW',
  );
}
